name: "Build (iOS)"

on:
  workflow_call:
    outputs:
      artifact-id:
        description: "Uploaded artifact ID"
        value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-26
            platform: ios

          - os: macos-26
            config: Simulator
            platform: ios-sim

      fail-fast: false

    runs-on: ${{ matrix.os }}

    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          rustup target add aarch64-apple-ios
          rustup target add aarch64-apple-ios-sim
          rustup target add x86_64-apple-ios

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Bootstrap build environment
        run: |
          ./mach --no-interactive bootstrap --application-choice "SpiderMonkey JavaScript engine"

      - name: Build SpiderMonkey
        run: |
          python3.11 ./build/ccl/build_spidermonkey.py --platform ${{ matrix.platform }}

      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v6
        with:
          name: SpiderMonkey iOS ${{ matrix.config }}
          path: spidermonkey*.zip
